name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy matplotlib scipy
        python -m pip install flake8 black pytest
        python -m pip install -e ./pysindy

    - name: Lint with flake8
      run: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=500 --statistics

    - name: Format check with Black
      run: |
        python -m black --check . --exclude "pysindy"

    - name: Run tests
      run: |
        python -m pytest -v --maxfail=1 --disable-warnings